# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doCellFromRowCol <- function(nrow, ncol, rownr, colnr, result) {
    invisible(.Call('raster_doCellFromRowCol', PACKAGE = 'raster', nrow, ncol, rownr, colnr, result))
}

